
export function displayLinks(links){
    const linksContainer = document.querySelector(".links-container") //gimme the 1st element that is part of a css class (itc ".links-container" ) & store in 'linksContainer'

    linksContainer.innerHTML = "" //clears the list of entries
    
    //  this code block loops through the links and renders them
    links.forEach(link => { // for each every link in some 'links' array...
        const div = document.createElement("div"); //...create an element <div> on-the-fly and store it into the 'div' variable for manipulation puproses.
                                                    // this along with the 'linksContainer' container in the DOM create the perfect space for any shortened urls that mihgt've
                                                    //been processed 
        div.classList.add("short-result"); //this adds CSS class 'short-result' to this div element, essentially styling the <div>.


        //because the the div is created on-the-fly, we get to implicitly define html elements that will hold/render any future input, output, generated by the user
        //ITC, the type of data being referred to is the original individual URL entered in by the user ('original' 'link' array item) & its resulting shortened URL
        // 'short' 'link' array item)
        // notice below the on-the-fly "copy-btn" element being created as well, which allows the user to directly interact with the output, itc, allows the user to copy the 
        // resulting shortened URL. 
        // This is wher ethe '.copy-btn' is born
        div.innerHTML = `
            <p><a href="${link.original}" target="_blank">${link.original}</a></p> 
            <p><a href="${link.short}" target="_blank">${link.short}</a></p>
            <button class="copy-btn">Copy</button>
        `;
        
        
        linksContainer.appendChild(div) // with the 'div' now containing BOTH data, this code line now renders/appends it to the linksContainer space.

        //clipboard functionality 
        const copyBtn = div.querySelector(".copy-btn") //this line prepares the '.copy-btn' for manipulation and stores it in 'copyBtn' variable.
        copyBtn.addEventListener("click", () => {  // we then add an event listenerto to the 'copyBtn', that when clicked upon....
            navigator.clipboard.writeText(link.short).then(() => {  // ..writed the resulting/shortened  URL to the clipboard...
                copyBtn.textContent = "Copied!" // at which point the message "Copied!" replaces the button's default message label "Copy"...
                copyBtn.disabled = true //...at which point the button's state becomes momentarily false (disabled)....
                setTimeout(() => {  //...at which point 'setTimeout(()' waits 2 seconds...
                    copyBtn.textContent = "Copy" //...before changing the button's current message label to "Copy"...
                    copyBtn.disabled = false //...and the buton becomes enabled once again, ready for the next 'on click' to run through this code block once again.
                }, 2000)
            });
        });
    });
}


